# Generated by Django 4.0.6 on 2022-08-14 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('country', models.CharField(choices=[('Nepal', 'Nepal'), ('India', 'India'), ('China', 'China'), ('Japan', 'Japan'), ('USA', 'USA'), ('England', 'England'), ('Germany', 'Germany'), ('Canada', 'Canada'), ('South Korea', 'South Korea'), ('Sri Lanka', 'Sri Lanka'), ('Bhutan', 'Bhutan'), ('Indonesia', 'Indonesia'), ('Singapore', 'Singapore'), ('Dubai', 'Dubai'), ('Sudia Arabia', 'Sudia Arabia'), ('Israel', 'Israel'), ('Argentina', 'Argentina'), ('Spain', 'Spain'), ('Brazil', 'Brazil')], default='Nepal', max_length=100)),
                ('address', models.CharField(blank='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
