# Generated by Django 4.0.6 on 2022-07-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data_name', models.CharField(default='Default Data', max_length=50)),
                ('title_image', models.ImageField(default='static/Birthday/images/title_images/title_icon_default.gif', upload_to='static/Birthday/images/title_images')),
                ('bd_date_text', models.CharField(default='20.12.2020 ', max_length=50)),
                ('reception_place', models.CharField(default=' Riddi Siddhi Party Palace, Suddhodhan-1, Pharsatikar', max_length=75)),
                ('default_invitation_msz', models.CharField(default='Mr. Bhaktaraj Bashyal and Mrs. Haridevi Bashyal request the honour of your presence on the auspicious occassion of the marriage ceremony of their son.', max_length=250)),
                ('about_me_image', models.ImageField(default='static/Birthday/images/aboutme/about_default.jpg', upload_to='static/Birthday/images/aboutme')),
                ('my_info', models.CharField(default='Hi! I am Ram Sharma currently pursing my job at Yeti International. I have completed my masters in MBA and bachelors in Computer Science. \nSuddhodhan-3, Bethani, Rupandehi', max_length=500)),
                ('my_address', models.CharField(default='Butwal-18, Bethani, Rupandehi', max_length=500)),
                ('footer_message', models.CharField(default=' Love, laughter and happily ever after. ', max_length=100)),
                ('bd_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.allorders')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(default='27.640382435658456', max_length=50)),
                ('latitude', models.CharField(default='83.30955395735835', max_length=50)),
                ('direction_info', models.CharField(default='Once you get Bethani, take Lumbini circuit road leading to West direction. Once you reach a Siyari river then take road towards North that leads directly to marriage location.', max_length=250)),
                ('palace_name', models.CharField(default='Buddhabhumi Party palace', max_length=50)),
                ('address', models.CharField(default='Rupandehi, Nepal', max_length=50)),
                ('contact_num', models.CharField(default='+977-1234567897', max_length=15)),
                ('email_or_fb_link', models.CharField(default='binary.science98@gmail.com', max_length=75)),
                ('birthday_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Birthday.birthdaydata')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='1234567898', max_length=10)),
                ('email', models.CharField(default='sample@email.com', max_length=500)),
                ('twitter_link', models.CharField(default='ttr.com', max_length=500)),
                ('fb_link', models.CharField(default='f.com', max_length=500)),
                ('yt_link', models.CharField(default='yt.com', max_length=500)),
                ('lnkd_link', models.CharField(default='link.com', max_length=500)),
                ('birthday_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Birthday.birthdaydata')),
            ],
        ),
    ]
