# Generated by Django 4.0.6 on 2022-07-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0002_rename_bd_order_birthdaydata_order_allorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdaydata',
            old_name='order_allorder',
            new_name='bd_order',
        ),
    ]
