# Generated by Django 4.0.6 on 2022-07-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data_name', models.CharField(default='Default Data', max_length=50)),
                ('title_image', models.ImageField(default='static/Marriage/images/title_images/title_icon_default.gif', upload_to='static/Marriage/images/title_images')),
                ('bride_groom_name', models.CharField(default='Ram & Sita', max_length=50)),
                ('marry_date_text', models.CharField(default='20.12.2020 ', max_length=50)),
                ('engagement_date', models.CharField(default='Friday, 2077 - 08 - 26 (11th December 2020) ', max_length=50)),
                ('wedding_day', models.CharField(default='Sunday, 2077 - 09 - 05 (20th December 2020) ', max_length=50)),
                ('janti_prasthan_time', models.CharField(default='10 a.m ', max_length=50)),
                ('janti_prsthan_place', models.CharField(default='Suddhodhan-3, Bethani, Rupandehi ', max_length=50)),
                ('reception_date', models.CharField(default='Tuesday, 2077 - 09 - 07 (22nd December 2020)', max_length=50)),
                ('reception_time', models.CharField(default=' From 3 P.M. to 8 P.M. ', max_length=50)),
                ('reception_place', models.CharField(default=' Riddi Siddhi Party Palace, Suddhodhan-1, Pharsatikar', max_length=75)),
                ('default_invitation_msz', models.CharField(default='Mr. Bhaktaraj Bashyal and Mrs. Haridevi Bashyal request the honour of your presence on the auspicious occassion of the marriage ceremony of their son.', max_length=250)),
                ('about_us_image', models.ImageField(default='static/Marriage/images/aboutus/about_default.jpg', upload_to='static/Marriage/images/aboutus')),
                ('groom_info', models.CharField(default='Hi! I am Ram Sharma currently pursing my job at Yeti International. I have completed my masters in MBA and bachelors in Computer Science. \nSuddhodhan-3, Bethani, Rupandehi', max_length=500)),
                ('bride_info', models.CharField(default='Hi! I am Neha Dahal currently working as leading architect in Lumbini Provinance. I have completed my masters in Civil Engineering from Oxford university.\nButwal-18, Bethani, Rupandehi', max_length=500)),
                ('groom_address', models.CharField(default='Butwal-18, Bethani, Rupandehi', max_length=500)),
                ('bride_address', models.CharField(default='Suddhodhan-3, Bethani, Rupandehi', max_length=500)),
                ('footer_message', models.CharField(default=' Love, laughter and happily ever after. ', max_length=100)),
                ('header_image', models.ImageField(default='static/Marriage/images/background/default_header_bg.jpg', upload_to='static/Marriage/images/background')),
                ('marriage_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.allorders')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_parents', models.CharField(default='Hajurbuwa, Hajurama', max_length=500)),
                ('parents', models.CharField(default='Thulobuwa/THuliama, uncle/aunt', max_length=500)),
                ('brothers', models.CharField(default='Thoulo dai/ thulibhauju, sanodai/ kanchi bhauju ', max_length=500)),
                ('sisters', models.CharField(default='Thulididi / Thulovinaju', max_length=500)),
                ('nephews', models.CharField(default='male/ female, female, male, ....', max_length=500)),
                ('cousins', models.CharField(default='male/ female, female, male, ....', max_length=500)),
                ('maternal', models.CharField(default='mama/ maiju, mama/maiju, ....', max_length=500)),
                ('marriage_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Marriage.marriagedata')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_father_fullname', models.CharField(default='Dr. Ghanshyam Sharma', max_length=50)),
                ('bride_mother_fullname', models.CharField(default='Dr. Radha Sharma', max_length=50)),
                ('groom_father_fullname', models.CharField(default='Prof. Vidya Bhandari', max_length=50)),
                ('groom_mother_fullname', models.CharField(default='Er. Shova Bhandari', max_length=50)),
                ('bride_father_image', models.ImageField(default='static/Marriage/images/parents/bd.png', upload_to='static/Marriage/images/parents')),
                ('bride_mother_image', models.ImageField(default='static/Marriage/images/parents/bm.png', upload_to='static/Marriage/images/parents')),
                ('groom_father_image', models.ImageField(default='static/Marriage/images/parents/gd.png', upload_to='static/Marriage/images/parents')),
                ('groom_mother_image', models.ImageField(default='static/Marriage/images/parents/gm.png', upload_to='static/Marriage/images/parents')),
                ('marriage_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Marriage.marriagedata')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(default='27.640382435658456', max_length=50)),
                ('latitude', models.CharField(default='83.30955395735835', max_length=50)),
                ('direction_info', models.CharField(default='Once you get Bethani, take Lumbini circuit road leading to West direction. Once you reach a Siyari river then take road towards North that leads directly to marriage location.', max_length=250)),
                ('palace_name', models.CharField(default='Buddhabhumi Party palace', max_length=50)),
                ('address', models.CharField(default='Rupandehi, Nepal', max_length=50)),
                ('contact_num', models.CharField(default='+977-1234567897', max_length=15)),
                ('email_or_fb_link', models.CharField(default='binary.science98@gmail.com', max_length=75)),
                ('marriage_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Marriage.marriagedata')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/Marriage/images/gallery')),
                ('detail', models.CharField(max_length=200)),
                ('marriage_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marriage.marriagedata')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='1234567898', max_length=10)),
                ('email', models.CharField(default='sample@email.com', max_length=500)),
                ('twitter_link', models.CharField(default='ttr.com', max_length=500)),
                ('fb_link', models.CharField(default='f.com', max_length=500)),
                ('yt_link', models.CharField(default='yt.com', max_length=500)),
                ('lnkd_link', models.CharField(default='link.com', max_length=500)),
                ('marriage_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Marriage.marriagedata')),
            ],
        ),
    ]
