# Generated by Django 4.0.6 on 2022-07-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marriage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marriagedata',
            old_name='marriage_order',
            new_name='order_allorder',
        ),
    ]
