# Generated by Django 4.0.6 on 2022-07-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marriage', '0002_rename_marriage_order_marriagedata_order_allorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marriagedata',
            old_name='order_allorder',
            new_name='marriage_order',
        ),
    ]
