# Generated by Django 4.0.6 on 2022-07-25 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(default='My Order', max_length=50)),
                ('time_of_purchase', models.DateTimeField(auto_now=True)),
                ('invitation_language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali'), ('wari', 'Newari'), ('hi', 'Hindi')], default='en', max_length=50)),
                ('order_status', models.CharField(choices=[('active', 'active'), ('expire', 'expire')], default='active', max_length=20)),
                ('payment_method', models.CharField(choices=[('Khalti', 'Khalti')], default='Khalti', max_length=20)),
                ('payment_completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=50)),
                ('theme_type', models.CharField(choices=[('Marriage', 'Marriage'), ('Birthday', 'Birthday'), ('Opening', 'Opening')], default='Marriage', max_length=15)),
                ('theme_link', models.CharField(default='themes_invitation/marriage/theme_n.html', max_length=50)),
                ('theme_color', models.CharField(default='pink', max_length=50)),
                ('sample_page_location', models.CharField(default='themes_sample/marriage/sample_theme_n.html', max_length=200)),
                ('description', models.CharField(default='This is detailed info for this Theme.', max_length=250)),
                ('theme_image', models.ImageField(default='static/core/theme_images/default.png', max_length=50, upload_to='static/core/theme_images')),
                ('theme_price', models.IntegerField(default=150)),
            ],
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('gender', models.CharField(blank=True, choices=[('Mr. ', 'Male'), ('Ms. ', 'Female')], max_length=5)),
                ('address', models.CharField(max_length=50)),
                ('inviteStatus', models.CharField(choices=[('Wedding', 'Wedding'), ('Reception', 'Reception'), ('_', '_')], default='W', max_length=20)),
                ('invitee_message', models.TextField(blank=True, default='This is default invitee message', max_length=500)),
                ('is_invitation_viewed', models.BooleanField(default=False)),
                ('secretCode', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.allorders')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans', models.CharField(choices=[('I', 'Indigo'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('O', 'Orange'), ('F', 'Free')], default='B', max_length=15)),
                ('no_of_days', models.IntegerField(default=7)),
                ('no_of_invitees', models.IntegerField(default=100)),
                ('plan_price', models.IntegerField(default=777)),
            ],
            options={
                'ordering': ['no_of_days'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_country', models.CharField(default='Nepal', max_length=20)),
                ('tax_state', models.CharField(default='Lumbini', max_length=20)),
                ('current_tax_rate', models.FloatField(default=5, max_length=6)),
                ('current_gst_rate', models.FloatField(default=12, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Wisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishes', models.CharField(max_length=500)),
                ('posted', models.DateTimeField(auto_now=True)),
                ('invitee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.invitee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.allorders')),
            ],
            options={
                'ordering': ['posted'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=25)),
                ('tax_rate', models.IntegerField(default=12)),
                ('amount_paid', models.IntegerField()),
                ('payment_choice', models.CharField(default='Khalti', max_length=2)),
                ('invitee_count', models.IntegerField()),
                ('plan_days', models.IntegerField()),
                ('invitation_book_PDF', models.FileField(blank=True, default=False, upload_to='')),
                ('time_of_purchase', models.CharField(max_length=25)),
                ('expire_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='allorders',
            name='plans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.plans'),
        ),
        migrations.AddField(
            model_name='allorders',
            name='selected_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.invitationthemes'),
        ),
        migrations.AddField(
            model_name='allorders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
